# DBHelper Deployment
# Handles database access
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbhelper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: dbhelper

  template:
    metadata:
      labels:
        component: dbhelper

    spec:
      containers:
        - name: databasehelper
          image: gabrielgelgor/dbhelper
          #imagePullPolicy: Never
          ports:
            - name: port5555
              containerPort: 5555
---
# DBHelper ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: dbhelper-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: dbhelper
  ports:
    - name: port5555
      port: 5555
      targetPort: 5555